School_site/config/routes.rb
Rails.application.routes.draw do
  resources :dashboard

  devise_for :users

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  root to: 'dashboard#index'

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'home' => 'pages#index', as: 'home'
  get 'about' => 'pages#about', as: 'about'
  get 'services' => 'pages#services', as: 'services'
  get 'contact' => 'pages#contact', as: 'contact'

end

School_site/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

School_site/app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :avatar
  after_commit :add_default_avatar, on: %i[create update]

  def avatar_thumbnail
    if avatar.attached?
      avatar.variant(resize:"150x150!").processed 
    else
      return "/default_profile.png"
    end
  end

  private
  def add_default_avatar
    unless avatar.attached?
       avatar.attach(
        io: File.open(
          Rails.root.join(
            'app', 'assets', 'images', 'default_profile.png'
          )
        ), filename: 'default_profile.png',
        content_type: 'image/png'
      )
    end
  end
end

School_site/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, 
    if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:avatar])
        devise_parameter_sanitizer.permit(:account_update, keys: [:avatar])
    end
end

School_site/app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
    @student = User.all
  end

  def show
    @students = User.find[:id]
  end
end

School_site/app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def index
        @title1= 'Hlomphanang College'
        @title2= 'Ring Commitment'
    end

    def about
    end

    def services
    end

    def contact
    end
end

School_site/app/controllers/registration_controller.rb
class RegistrationsController < Devise::RegistrationsController
    private

    def sign_up_params
        params.require(:user).permit(:name, :username, :phone, :studentnumber, :email, :password, :password_confirmations)
    end

    def account_update_params
        params.require(:user).permit(:name, :username, :phone, :studentnumber, :email, :password, :password_confirmation, :current_password)
    end
end

School_site/app/helpers/application_helper.rb
module ApplicationHelper
end

School_site/app/helpers/dashboard_helper.rb
module DashboardHelper
end

School_site/app/helpers/pages_helper.rb
module PagesHelper
end

School_site/app/helpers/users_helper.rb
module UsersHelper
end

School_site/app/views/dashboard/index.html.erb
<%= render 'partials/alerts' %>
      <nav class="navbar navbar-dark sticky-top bg-light flex-md-nowrap p-0 shadow">
    <%= link_to 'HLOMPHANANG COLLEGE', root_path, class:"navbar-brand col-md-3 col-lg-2 mr-0 px-3 text-dark" %>
    <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-toggle="collapse" data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="btn-group dash_nav">
    
    <i class=" nav_user_icon dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <%= image_tag(current_user.avatar_thumbnail, :class => "rounded") %>
    </i>
    <div class="dropdown-menu">
      <li><%= link_to 'Edit Profile', edit_user_registration_url, class: 'dropdown-item' %></li>
      <li><%= link_to "Delete Profile", cancel_user_registration_url, data: { confirm: "Are you sure?" }, method: :delete, class: 'dropdown-item' %></li>
      <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete,  class: 'dropdown-item' %></li>
      <div class="dropdown-divider"></div>
      <li><%= link_to 'Contact Us', edit_user_password_url, class: 'dropdown-item' %></li>
    </div>
  </div>
  </nav>

  <div class="container-fluid">
    <div class="row">
       
        <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block side sidebar collapse">
            <div class="d-flex justify-content-center mt-4">
            <%= image_tag(current_user.avatar_thumbnail, :class => "rounded-circle user_dashboard_img") %>
              </div>
              <p class="ml-4 text-white"><%= current_user.email %></p>
        <div class="sidebar-sticky stick pt-3">
             
          <ul class="nav flex-column" id="myTab">
              
            <li class="nav-item results-tab1 myTable2" data-target="tab_1">
              <a class="nav-link active" data-toggle="tab1" href="#">
                <i class="bx bxs-grid-alt"></i>
                Dashboard <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item res results-tab1">
              <a class="nav-link" id="results-tab" data-toggle="tab2" href="#results">
                <i class="bx bxs-id-card "></i>
                Results
              </a>
            </li>
            <li class="nav-item results-tab1">
              <a class="nav-link" id="report-tab" data-toggle="tab3" href="#report">
                <i class="bx bxs-report  "></i>
                Reports
              </a>
            <li class="nav-item results-tab1">
              <a class="nav-link" id="teacher-tab" data-toggle="tab4" href="#teacher_details">
                <i class="bx bxs-spreadsheet"></i>
                Teacher Details
              </a>
            </li>
            </li>
            <li class="nav-item results-tab1">
              <a class="nav-link" id="register-tab" data-toggle="tab5" href="#registration">
                <i class="bx bxs-user"></i>
                Registration Status
              </a>
            </li>
          </ul>
  
          <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
            <span>Saved reports</span>
            <a class="d-flex align-items-center text-muted" href="#" aria-label="Add a new report">
            </a>
          </h6>
          <ul class="nav flex-column mb-2">
            <li class="nav-item">
              <a class="nav-link" href="#">
                <i class="bx bx-file"></i>
                Current Semester
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <i class="bx bx-file"></i>
                Last quarter
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <i class="bx bx-file"></i>
                Social engagement
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <i class="bx bx-file"></i>
                Upcoming Events
              </a>
            </li>
          </ul>
        </div>
      </nav>
  
      <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
          <h2 class="h2">Welcome name</h2>
          <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group mr-2">
              <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
              <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
            </div>
            <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
              <span data-feather="calendar"></span>
              This week
            </button>
          </div>
        </div>
  
       
  <!-- This is for the DASHBOARD -->
        <h2>Meet class of 2021 Grade 10a</h2>
        <div class="table-responsive">
          <div class="myTable tab1" id="table">
          <table class="table table-striped table-sm">
            <thead>
              <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Surname</th>
                <th>Position</th>
                <th>Semester Score</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>1,001</td>
                <td>Bongani</td>
                <td>Phala</td>
                <td>School President</td>
                <td>98%</td>
              </tr>
              <tr>
                <td>1,002</td>
                <td>Tintswalo</td>
                <td>Maluleke</td>
                <td>School Treasurer</td>
                <td>99%</td>
              </tr>
              <tr>
                <td>1,003</td>
                <td>Integer</td>
                <td>nec</td>
                <td>odio</td>
                <td>Praesent</td>
              </tr>
              <tr>
                <td>1,003</td>
                <td>libero</td>
                <td>Sed</td>
                <td>cursus</td>
                <td>ante</td>
              </tr>
              <tr>
                <td>1,004</td>
                <td>dapibus</td>
                <td>diam</td>
                <td>Sed</td>
                <td>nisi</td>
              </tr>
              <tr>
                <td>1,005</td>
                <td>Nulla</td>
                <td>quis</td>
                <td>sem</td>
                <td>at</td>
              </tr>
              <tr>
                <td>1,006</td>
                <td>nibh</td>
                <td>elementum</td>
                <td>imperdiet</td>
                <td>Duis</td>
              </tr>
              <tr>
                <td>1,007</td>
                <td>sagittis</td>
                <td>ipsum</td>
                <td>Praesent</td>
                <td>mauris</td>
              </tr>
              <tr>
                <td>1,008</td>
                <td>Fusce</td>
                <td>nec</td>
                <td>tellus</td>
                <td>sed</td>
              </tr>
              <tr>
                <td>1,009</td>
                <td>augue</td>
                <td>semper</td>
                <td>porta</td>
                <td>Mauris</td>
              </tr>
              <tr>
                <td>1,010</td>
                <td>massa</td>
                <td>Vestibulum</td>
                <td>lacinia</td>
                <td>arcu</td>
              </tr>
              <tr>
                <td>1,011</td>
                <td>eget</td>
                <td>nulla</td>
                <td>Class</td>
                <td>aptent</td>
              </tr>
            </tbody>
          </table>
        </div>
           <!-- This is for the Results -->
        <div id="results" class="tab_2 myTable2">
          <h1>Hello Results</h1>
        </div>
        <!-- This is for the Report -->
        <div id="report" class="report tab_3 myTable3">
          <h1>Hello Report</h1>
        </div>
        <!-- This is for the Teacher Details -->
        <div id="teacher_details" class="teacher tab_4 myTable4">
          <h1>Hello Teacher Details</h1>
        </div>
        <!-- This is for the Registration -->
        <div id="registration" class="registration tab_5 myTable5">
          <h1>Hello Registration</h1>
        </div>
        </div>
       
      </main>
    </div>
  </div>
 

School_site/app/views/dashboard/show.html.erb
<h1>Dashboard#show</h1>
<p>Find me in app/views/dashboard/show.html.erb</p>

School_site/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>College</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href='https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css' rel='stylesheet'>
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@300&display=swap" rel="stylesheet"> 
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href='https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css' rel='stylesheet'>
  
    </head>
    <body>

    <%= yield %>
  </body>
</html>

School_site/app/views/pages/about.html.erb
<%= render 'partials/navbar' %>
</h1>About</h1>

School_site/app/views/pages/contact.html.erb
<%= render 'partials/navbar' %>
<h1>Contact</h1>

School_site/app/views/pages/index.html.erb
<%= render 'partials/navbar' %>
<div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active image1">
        <div class="intro">
            <h1 class="text-white"><%= @title1%></h1>
            <h3 class="text-white">Brotherhood</h3>
        </div>
    </div>
    <div class="carousel-item image2">
        <div class="intro">
            <h1 class="text-white"><%= @title2%></h1>
            <h3 class="text-white">Bright Future</h3>
        </div>
    </div>
    <div class="carousel-item image3">
    </div>
    <div class="carousel-item image4">

    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
    <span class="sr-only">Next</span>
  </a>
</div>

<section class="container-fluid">
    <div class="container-fluid welcome mt-5">
        <h2><strong>Welcome</strong> to Hlomphanang College</h2>
        <hr class="line mt-5">    
    </div>

    <div class="introduction mt-4">
        <div class="container-fluid int">
            <ul>
                <li>GROWING UP AT THE COLLEGE</li>
                <li>HLOMPHANAN'S WEEKLY NEWS</li>
            </ul>
            <div class="row">
                    <div class="col-md-3">
                        <%= image_tag("intro1.jpg", width: 150) %>
                        <div class="aca mt-3">
                            <h4>ACADEMICS</h4>
                            <p>
                                All students at St Alban's College have the opportunity for a positive educational experience that is tailored to meet their evolving stages of cognitive development, and expert Staff ensure high quality learning.
                            </p>
                            <%= link_to 'Read more>>',  services_path %>
                        </div>
                        
                    </div>
                    <div class="col-md-3">
                        <div class="myimg">
                        <%= image_tag("intro2.jpg",width: 150, height: 225) %>
                        </div>
                        <div class="aca mt-3">
                        <h4>SPORTS</h4>
                        <p>
                            All students at St Alban's College have the opportunity for a positive educational experience that is tailored to meet their evolving stages of cognitive development, and expert Staff ensure high quality learning.
                        </p>
                        <%= link_to 'Read more>>',  services_path %>
                    </div>
                    </div>
                    <div class="col-md-3">
                        <%= image_tag("intro3.jpg", width: 150) %>
                        <div class="aca mt-3">
                        <h4>ARTS AND CULTURE</h4>
                        <p>
                            All students at St Alban's College have the opportunity for a positive educational experience that is tailored to meet their evolving stages of cognitive development, and expert Staff ensure high quality learning.
                        </p>
                        <%= link_to 'Read more>>',  services_path %>
                    </div>
                    </div>
                    <div class="col-md-3 news ">
                       <div class="container-fluid mt-3">
                            <div class="row">
                                <div class="col-md-6">
                                    <%= image_tag("art1.JPG", width: 100) %>
                                </div>
                                <div class="col-md-6">
                                    <h6><strong>31 Jul 2020</strong></h6>
                                    <small><%= link_to 'Final Assembly Trinity', services_path %></small>
                                </div>
                            </div>
                            <div class="row mt-5">
                            <div class="col-md-6">
                                <%= image_tag("art2.JPG", width: 100) %>
                            </div>
                            <div class="col-md-6">
                                <h6><strong>31 Jul 2020</strong></h6>
                                <small><%= link_to 'Investec Focus', services_path %></small>
                            </div>
                        </div>
                        <div class="row mt-5">
                        <div class="col-md-6">
                            <%= image_tag("art3.JPG", width: 100, height: 100) %>
                        </div>
                        <div class="col-md-6">
                            <h6><strong>02 May 2020</strong></h6>
                            <small><%= link_to 'POLICY DOCUMENTATION', services_path %></small>
                        </div>
                    </div>
                       </div>
                    </div>
                    <div class="more ml-auto">
                    <p><%= link_to 'Click for more news >>', services_path %></p>
                    </div>
            </div>
        </div>
        <%=link_to 'SA COVID-19 Website', services_path, class:'btn btn-info' %>
    </div>
</section>

<section class="container-fluid mt-5">
    <div class="row">
        <div class= "col-md-4">
            <%= image_tag("vision.png", height:450) %>
        </div>
        <div class= "col-md-8">
            <%= image_tag("leadership.jpg", width: 150, height:450) %>
        </div>
    </div>

</section>
<hr class="mt-4">
<footer>
    <div class="container myfooter">
        <div class="text-center">
            <p><strong>Physical Address</strong> 110 Clearwater Road, Lynnwood Glen, Pretoria</p>
            <p><strong>Postal Address</strong> Private bag X27 Sosh, Pretoria</p>
        </div>
        <ul>
            <li><i class="bx bxl-facebook-square bx-md bx-border-circle"></i> </li>
            <li><i class="bx bxl-linkedin-square bx-md bx-border-circle"></i> </li>
            <li><i class="bx bxl-twitter bx-md bx-border-circle"></i> </li>
            <li><i class="bx bxl-instagram bx-md bx-border-circle"></i> </li>
        </ul>
        </div>
        <%=image_tag('footer-image.png') %>
</footer>

School_site/app/views/pages/services.html.erb
<%= render 'partials/navbar' %>
<h1>Services</h1>

School_site/app/views/partials/_alerts.html.erb
<section class= "container text-center">
<% if notice %><p class="alert alert-success"><a class="close" data-dismiss="alert">&times;</a><%= notice %></p><% end %>
<% if alert %><p class="alert alert-error"><a class="close" data-dismiss="alert">&times;</a><%= alert %></p><% end %>
</section>

School_site/app/views/partials/_dashboard.html.erb
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
<h5 class="my-0 mr-md-auto font-weight-normal ml-auto"><%= link_to 'HLOMPHANANG COLLEGE', home_path, class:"logo_tag" %></h5>
<nav class="my-2 my-md-0 mr-md-3">
<%= link_to 'MY HOME PAGE', home_path, class:"mr-5" %>
  <%= link_to 'MY DASHBOARD', new_user_session_url, class: "mr-3" %>
</nav>
<%= link_to 'Sign up', new_user_registration_url, class: "btn btn-outline-primary" %>
</div>

School_site/app/views/partials/_edit.html.erb
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
<h5 class="my-0 mr-md-auto font-weight-normal ml-auto"><%= link_to 'HLOMPHANANG COLLEGE', root_path, class:"logo_tag" %></h5>
<nav class="my-2 my-md-0 mr-md-3">
<%= link_to 'BACK TO DASHBOARD', root_path, class:"mr-5" %>
</nav>
<%= link_to 'CONTACT ADMIN', new_user_registration_url  %>
</div>

School_site/app/views/partials/_loginnav.html.erb
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
<h5 class="my-0 mr-md-auto font-weight-normal ml-auto"><%= link_to 'HLOMPHANANG COLLEGE', home_path, class:"logo_tag" %></h5>
<nav class="my-2 my-md-0 mr-md-3">
<%= link_to 'MY HOME PAGE', home_path, class:"mr-5" %>
  <%= link_to 'MY DASHBOARD', new_user_session_url, class: "mr-3" %>
</nav>
<%= link_to 'Sign up', new_user_registration_url, class: "btn btn-outline-primary" %>
</div>

School_site/app/views/partials/_navbar.html.erb
<nav class='navbar'>
    <div class='container'>
        <h3><%= link_to 'Hlomphanang High', home_path, class:'logo navlist' %></h3>
        <ul class='nav'>
            <li><%= link_to 'About', about_path , class:'navlist' %></li>
            <li><%= link_to 'Academics', services_path, class:'navlist' %></li>
            <li><%= link_to 'Admissions', contact_path, class:'navlist' %></li>
        </ul>
        <ul class='register'>
            <% if current_user %>
                <li><%= link_to 'Sign Out', destroy_user_session_url, class: 'navlist', method: :delete %></li>
                <% else %>
                <li><%= link_to 'Sign Up', new_user_registration_url, class:'navlist btn btn-primary' %></li>
                <li><%= link_to 'Sign In', new_user_session_url, class:'navlist btn btn-primary' %></li>
            <% end %>
            
        </ul>
    </div>
</nav>

School_site/app/views/partials/_signup.html.erb
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
<h5 class="my-0 mr-md-auto font-weight-normal ml-auto"><%= link_to 'HLOMPHANANG COLLEGE', home_path, class:"logo_tag" %></h5>
<nav class="my-2 my-md-0 mr-md-3">
<%= link_to 'MY HOME PAGE', home_path, class:"mr-5" %>
  <%= link_to 'MY DASHBOARD', new_user_session_url, class: "mr-3" %>
</nav>
<%= link_to 'Sign in', new_user_session_url, class: "btn btn-outline-primary" %>
</div>

School_site/app/views/partials/alerts.html.erb
<% if notice %><p class="alert alert-success"><a class="close" data-dismiss="alert">&times;</a><%= notice %></p><% end %>
<% if alert %><p class="alert alert-error"><a class="close" data-dismiss="alert">&times;</a><%= alert %></p><% end %>